### ISSUE TITLE
Add verbosity options

### ISSUE THREAD

**Issue by Svalorzen** [Svalorzen/AI-Toolbox#11]
Each implemented algorithm should provide `setVerbosity``getVerbosity` methods in order to allow the user to have some insight as to what is going on during long computations.

**Comment by Svalorzen** [comment]
Actually, no. Each method should simply log using global logging functions (info, warning, debug, etc..). It should be possible to turn off logging completely with a compile flag for maximum speed. If not turned off, logging should be configurable somehow to report only certain levels as needed by the user.

**Comment by alecive** [comment]
How do you think to implement the logging? Are you going to do a logging system on your own or use some external tools?

**Comment by Svalorzen** [comment]
We could just start with simple `std::cout` and `std::cerr`, and then go from there. The idea in any case is that the wrapper interface is there so that the user can then just modify the wrappers' internals and use whatever logging solution they like.

ZLog in case looks like a nice library to use later, when stuff actually logs.

**Comment by alecive** [comment]
It is the best way to proceed imho. If not too complex to implement, you should also take a look at the ROS logging suite (which works fine for me).

**Comment by Svalorzen** [comment]
Actually, at this point, I think it's better to use Boost Log. The dependency we already have, and the trivial logging seems simple enough for what we need.

**Comment by alecive** [comment]
I agree (didn't know about boost log) :+1:

**Comment by Svalorzen** [comment]
I'm currently working on this issue.

The actual best way to go, I've realized, is just to expose a set of C++ macros, that if defined by the user will be used in order to log. This is because we are a library, and we have no right to impose any specific logging framework to the user. This includes deciding where to send logs and so on.

I'll be adding a page to the Doxygen documentation in order to explain how it's supposed to work and what the user needs to do in order to enable logging in the library.

At the same time, if logging is disabled, we'll create fake logging facilities which will be optimized away by the compiler, but will enable us to check the code for syntax errors anyway.

**Comment by Svalorzen** [comment]
The latest commit fc5c741964454c1e12f8851df9ccfb6c946e42dd fixes the "how". Now the only thing missing is to actually add the logging statements.

This will probably get done over time as I or other users need them. I'm leaving this open for now just in case if there's problems, otherwise I'll close this and open another issue just asking to add log statements where needed.
