### ISSUE TITLE
MDP can not be compiled with cmake 2.8

### ISSUE THREAD

**Issue by aukejw** [Svalorzen/AI-Toolbox#14]
Due to a Python version mismatch, cmake 2.8 can not find the python binary:
```
auke@auke-GS60-2QE:~/AI-Toolbox/build$ cmake -DCMAKE_BUILD_TYPE=Release ..
-- Boost version: 1.54.0
CMake Error at /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:108 (message):
  Could NOT find PythonLibs: Found unsuitable version "2.7.6", but required
  is exact version "2.7" (found /usr/lib/x86_64-linux-gnu/libpython2.7.so)
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:313 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-2.8/Modules/FindPythonLibs.cmake:208 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  src/CMakeLists.txt:10 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/auke/AI-Toolbox/build/CMakeFiles/CMakeOutput.log".
```

This issue can be solved by [upgrading to cmake >3.0](http://askubuntu.com/questions/610291/how-to-install-cmake-3-2-on-ubuntu-14-04), as specified in [this stackoverflow answer](http://stackoverflow.com/questions/29245558/how-to-link-with-python3-libs-with-cmake).

What cmake version are you using? Perhaps you can specify that cmake >3 is needed, or alternatively include a 'known issues' tab in the readme?

**Comment by Svalorzen** [comment]
Sorry, I was playing with the EXACT cmake thing to find the right python libraries. In theory Python 3 should work, since Boost::Python does support it, but in practice it seems that test fail if you link with that - as travis notices.

I now removed the exact, so you shouldn't have that problem anymore. If travis still complains, I'll try to understand better what the problem is.

**Comment by Svalorzen** [comment]
Travis now says everything is alright. Let me know if it works for you, then I can close this =)

**Comment by aukejw** [comment]
Confirmed to work!
