### ISSUE TITLE
Compilation issues

### ISSUE THREAD

**Issue by alecive** [Svalorzen/AI-Toolbox#16]
Hello @Svalorzen , I've got the following issues while compiling your software:

```
(~/code/AI-Toolbox/build) (master) 
[alecive@malakim]$ make 
Scanning dependencies of target AIToolboxMDP
[  1%] Building CXX object src/CMakeFiles/AIToolboxMDP.dir/Impl/Seeder.cpp.o
[  3%] Building CXX object src/CMakeFiles/AIToolboxMDP.dir/MDP/Experience.cpp.o
[  4%] Building CXX object src/CMakeFiles/AIToolboxMDP.dir/MDP/Utils.cpp.o
In file included from /home/alecive/code/AI-Toolbox/include/AIToolbox/MDP/Utils.hpp:5:0,
                 from /home/alecive/code/AI-Toolbox/src/MDP/Utils.cpp:1:
/home/alecive/code/AI-Toolbox/include/AIToolbox/MDP/Types.hpp:120:111: error: expected primary-expression before ‘,’ token
                         static_cast<double (Z::*)(size_t,size_t,size_t) const>  (&Z::getTransitionProbability),
                                                                                                               ^
/home/alecive/code/AI-Toolbox/include/AIToolbox/MDP/Types.hpp:218:105: error: expected primary-expression before ‘,’ token
                         static_cast<long unsigned   (Z::*)(size_t,size_t,size_t) const>  (&Z::getVisits),
                                                                                                         ^
make[2]: *** [src/CMakeFiles/AIToolboxMDP.dir/MDP/Utils.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/AIToolboxMDP.dir/all] Error 2
make: *** [all] Error 2
```

To complete the issue, here is the output of my cmake step:
```
(~/code/AI-Toolbox/build) (master) 
[alecive@malakim]$ cmake -DCMAKE_BUILD_TYPE=Release -DMAKE_MDP=1 -DMAKE_PYTHON=1 .. # Will build MDP and Python libraries
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Boost version: 1.54.0
-- Found Eigen3: /usr/include/eigen3 (Required is at least version "2.91.0") 
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython2.7.so (found suitable version "2.7.6", minimum required is "2.7") 
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   python
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   unit_test_framework
-- Found PythonInterp: /usr/bin/python2.7 (found suitable exact version "2.7.6") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/alecive/code/AI-Toolbox/build
```

Any hint?

**Comment by Svalorzen** [comment]
Hey, I see that you're using g++ 4.8. As explained in the README, unfortunately g++ 4.8 has a couple of bugs that will break the build. Can you try with g++ >= 4.9 and see if it works?

**Comment by alecive** [comment]
Good to know. I'm closing this issue. Two suggestions: 

 * I would add a subsection called **Dependencies** in order to make them easier to find (instead of a paragraph inside the build instructions)
 * It seems that cmake `v3.0` is not needed. Everything was configured properly with cmake `v2.8`. It would be better to be compatible with older versions if newer features are not needed!

Anyway, thanks for the help!

**Comment by alecive** [comment]
Good to know. I'm closing this issue. Two suggestions: 

 * I would add a subsection called **Dependencies** in order to make them easier to find (instead of a paragraph inside the build instructions)
 * It seems that cmake `v3.0` is not needed. Everything was configured properly with cmake `v2.8`. It would be better to be compatible with older versions if newer features are not needed!

Anyway, thanks for the help!

**Comment by alecive** [comment]
Good to know. I'm closing this issue. Two suggestions: 

 * I would add a subsection called **Dependencies** in order to make them easier to find (instead of a paragraph inside the build instructions)
 * It seems that cmake `v3.0` is not needed. Everything was configured properly with cmake `v2.8`. It would be better to be compatible with older versions if newer features are not needed!

Anyway, thanks for the help!
