### ISSUE TITLE
the pomcp solver of AI_Toolbox

### ISSUE THREAD

**Issue by yujianyuanhaha** [Svalorzen/AI-Toolbox#30]
is the pomcp solver(I see pomdp value iteration work, while not of pomcp) of AI_Toolbox implemented or not? Or is there any example I can test the pomcp codes?

**Comment by Svalorzen** [comment]
Hey, POMCP is indeed implemented, you can find it in the `include/AIToolbox/POMDP/Algorithms` folder. As for the examples, there are a couple of tests for the algorithm in the `test/POMDP/Algorithms/POMCPTests.cpp` file.

I also actually implement `rPOMCP`, which is a variant of the algorithm which I made for my master thesis, which is useful to solve POMDPs where rewards are a function of the beliefs. Just in case you need it =)

Let me know if anything in the docs is unclear!

**Comment by Svalorzen** [comment]
Did you manage to find the implementation? If so, I'd close this issue.
