### ISSUE TITLE
Example that uses Cassandra parser?

### ISSUE THREAD

**Issue by hifzajaved** [Svalorzen/AI-Toolbox#33]
Is there any example code or documentation available on using the Cassandra parser for a POMDP model? When you say it parses a reasonable subset of the Cassandra POMDP format, what exactly do you mean?

**Comment by Svalorzen** [comment]
You can see an example [here](https://github.com/Svalorzen/AI-Toolbox/blob/07b07fc3601a59ced8652b73f36c72e330006e1d/test/POMDP/ModelTests.cpp#L133) (with the corresponding POMDP file [here](https://github.com/Svalorzen/AI-Toolbox/blob/master/test/data/ejs4.POMDP)).

There are some limitation, for example I don't yet parse labels, so you can't have them. The reward function must be specified as a table by action-state only. I don't yet support the value label (so I only accept R in terms of rewards). I think this are the only limitations IIRC. In any case, the code can be improved, and if you pass it something it doesn't like it should give you a reasonable error when trying to parse.
