### ISSUE TITLE
model.getRewardFunction()

### ISSUE THREAD

**Issue by hifzajaved** [Svalorzen/AI-Toolbox#34]
Hello,
I referred to your tiger_door project to create my own POMDP model that involves human behavior modeling. I noticed that in this example, the rewards are dependent only on the current state and action. In my case, however, the rewards are determined by the last state and the current state.
I noticed that the function getRewardFunction() returns a matrix that has S rows and A columns. What I'm looking for though is a reward function that is the same for all actions, depending only on the change in states- meaning it would have S rows and S columns.
Is there a different function that I need to use to implement such a scenario?

**Comment by zsunberg** [comment]
I'm not familiar with this software, but we have often come across this issue in developing [POMDPs.jl](https://github.com/JuliaPOMDP/POMDPs.jl). In that software, the reward is defined in terms of the current state, action, and next state (s, a, and s'), but some solvers require a reward function that's only dependent on s and a, just like you describe.

I think that if you just define the s-a reward function as the *expectation* of the s-a-s' reward function, that is

![image](https://user-images.githubusercontent.com/4240491/50846565-b9e82b80-132c-11e9-9a56-eba378df2127.png)
most algorithms should find a solution that is equivalent to the case where you defined R(s,a,s').

**Comment by hifzajaved** [comment]
> I'm not familiar with this software, but we have often come across this issue in developing [POMDPs.jl](https://github.com/JuliaPOMDP/POMDPs.jl). In that software, the reward is defined in terms of the current state, action, and next state (s, a, and s'), but some solvers require a reward function that's only dependent on s and a, just like you describe.
> 
> I think that if you just define the s-a reward function as the _expectation_ of the s-a-s' reward function, that is
> 
> ![image](https://user-images.githubusercontent.com/4240491/50846565-b9e82b80-132c-11e9-9a56-eba378df2127.png)
> most algorithms should find a solution that is equivalent to the case where you defined R(s,a,s').

Thanks for your response.
Can you tell me which solvers in your library (offline and online) accept the s-a-s' reward function?

**Comment by hifzajaved** [comment]
Thanks, @zsunberg !

**Comment by Svalorzen** [comment]
@hifzajaved Btw, I've checked again and the the POMDP example rewards are defined as an [SxAxS' matrix](https://github.com/Svalorzen/AI-Toolbox/blob/865f13af1b604bde773d18ebb2bb4594e7dcb259/examples/POMDP/tiger_door.cpp#L130), so I'm still not sure where the problem is..
