### ISSUE TITLE
Question about function approximation.

### ISSUE THREAD

**Issue by drlCoder** [Svalorzen/AI-Toolbox#38]
Does the library provide any facilities for generalisation and value function approximation ? (e.g. simple Q-Learning with linear function approximation)

**Comment by Svalorzen** [comment]
The `Factored` part of the library does use linearly factored QFunctions. At the moment there's not that much stuff yet (Sparse Cooperative Q-Learning and the multi-agent Linear Programming are the main ones), but more stuff is to come. I already have some code for something similar to what you suggest, but I'm waiting to put it online until I can get it published :)

**Comment by Svalorzen** [comment]
If you have suggestions for methods feel free to add them to issue #7!

**Comment by drlCoder** [comment]
Awesome ! Really great. Are you also considering deep RL ?

**Comment by Svalorzen** [comment]
Not at the moment. I think deep RL is a bit outside the scope of this library for now, and as it stands there's quite a lot of other repositories which are probably better suited for the task, so I'm trying to avoid duplicating their work..

**Comment by drlCoder** [comment]
Thank you.
