### ISSUE TITLE
Building LP Solve

### ISSUE THREAD

**Issue by opyr** [Svalorzen/AI-Toolbox#43]
Building on Windows 10.
Having trouble getting AI-Toolbox to recognize LP Solve.
We followed the other issue #32 suggestions but it still doesn't work.

```
-- Found Boost: C:/MinGW/include (found suitable version "1.71.0", minimum required is "1.59")
-- Found Eigen3: C:/Program Files/eigen3 (Required is at least version "3.2.92")
CMake Error at C:/Program Files/CMake/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:164 (message):
  Could NOT find LpSolve (missing: LPSOLVE_LIBRARIES)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:445 (_FPHSA_FAILURE_MESSAGE)
  cmake/Modules/FindLpSolve.cmake:91 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:151 (find_package)
```
Here is what we are running to build:
```
rm -rf build
mkdir build
cd build
cmake .. \
  -DLPSOLVE_LIBRARIES="C:\Program Files\lpsolve"\
  -DLPSOLVE_INCLUDE_PATH="C:\Program Files\lpsolve"\
  -DLPSOLVE_LINKS="C:\Program Files\lpsolve"\
  -A x64\
```

**Comment by Svalorzen** [comment]
What I usually do in these cases is go inside the `FindLpSolve.cmake` file (in the `cmake/Modules` folder) and edit it to add some debugging statements.

You can do this by simply adding some `message("my_message ${my_var}")` statements inside the various `if` branches of the script, and at least you can figure out whether CMake is finding the library, if it can use it to compile and so on.

For example, you could put at line 28 something like:

    message("Found basic path to lp_lib.h as ${LPSOLVE_INCLUDE_PATH}")

Be sure you have the `.lib` version of the library as the `.a` and `.so` version will not work.

Having to debug CMake is unfortunately annoying, but I have found it is a necessity on Windows given the non-existence of default paths (and also given that the scripts we use to find LpSolve and Eigen are not officially from CMake and I'm not that much of a CMake expert to make them more foolproof).

Let me know if you manage to figure out exactly which step breaks.

**Comment by opyr** [comment]
Tried a bunch of things, including putting a copy of lpsolve55.dll in System32 and a number of other locations.  Finally, I managed to stop the "missing" errors but wound up with "Could not link against lpsolve55!" error.  This one is very difficult to troubleshoot, but compiling a test .cpp file came back with an error about linking to dlfcn.h.  This file exists in the MinGW/include folder.

Tried installing on OSX machine.  The library name is not 'lpsolve55.a' but 'liblpsolve55.a'.  Are you aware of that fact?  So, on the Apple machine, the error remains as "Missing: LPSOLVE_LIBRARIES".

So I'm unable to build on either platform.

**Comment by Svalorzen** [comment]
I've never used MinGW to compile the library to be honest, my tests with Windows were always with Visual Studio.

On Mac, and also on Linux, library files are always prefixed with "lib". It's normal, and the build system expects it and automatically adjusts for it. But I think on a Mac the library should have the suffix `.dylib`, not `.a`. In issue #35 and #41 two people managed to build the library on Mac, and you can see from their logs that it is the case.

Not sure where they got the library though, as I'm unfamiliar with Macs.

**Comment by Svalorzen** [comment]
Hi, did you manage to make it work? If you don't need help anymore otherwise I can close this issue.
