### ISSUE TITLE
Save POMDP policy

### ISSUE THREAD

**Issue by jocacace** [Svalorzen/AI-Toolbox#50]
Hi to all, 
I am new of AI-Toolbox. I properly set and test my POMDP problem. However, I am searching for a method to save the policy after that it has been solved. My problem is quite huge (more than 100 states). Is there a method to save the policy, loading it when my POMDP node starts?

**Comment by Svalorzen** [comment]
Hey, I think you should be able to use an `std::ofstream` to just dump the policy into a file, and reload it similarly. See:

http://svalorzen.github.io/AI-Toolbox/namespaceAIToolbox_1_1POMDP.html#a46eee8111107489e3d68d30055722ed8
http://svalorzen.github.io/AI-Toolbox/namespaceAIToolbox_1_1POMDP.html#a17b5a1ad1cf5759d34c6a8470089f9e1

**Comment by jocacace** [comment]
Thank you so much for the quick and kindly reply! 
I will look to that, 

Regards.

**Comment by jocacace** [comment]
Dear Svalorzen,

Do you have an example in which these functions are used? From the doc I am not able to make them working properly

**Comment by Svalorzen** [comment]
Hey, I'm replying here since I like to keep issues public. I've tested the code again just to check that no bugs had crept up in the meantime, and also added an IO test to be sure. I'll push them in a bit.

Can you tell me exactly what you tried to do, what errors you got and what you were expecting? This also helps me figure out how to improve the docs for other people.

**Comment by jocacace** [comment]
Dear @Svalorzen. Again thank you. 

My idea was to retrieve the policy saving it into a text file, in order to load it later. For this reason I tried the following code:
`

    
AIToolbox::POMDP::Policy policy(S, A, O, std::get<1>(solution));
ofstream f;
f.open("/tmp/policy.txt",  std::ofstream::out | std::ofstream::app);
f << policy;


However, this code gave me a compilation error, because my compiler was not able to find the correct overload of the operator. Of course, should be an error in my code. More or less, the same thing happens with the >> operator. 

`

**Comment by jocacace** [comment]
Shame on me!!!
Thanks a lot.. I completely forget to include the header
