### ISSUE TITLE
Problem with make

### ISSUE THREAD

**Issue by CassandroMartinho** [Svalorzen/AI-Toolbox#53]
Hello again, 

Sorry to be bothering you with this simple error but I installed a new ubuntu environment and I can't seem to compile the library. I've tried with a old version of the library and it worked but the current master branch doesn't seem to work.

The problem occurs after the "cmake .." when I try to run make I have an error on that goes:
```
[  2%] Building CXX object src/CMakeFiles/AIToolboxMDP.dir/Utils/Probability.cpp.o
In file included from /home/goldencrow/Documents/secondstest/AI-Toolbox-master/include/AIToolbox/Utils/Probability.hpp:8,
                 from /home/goldencrow/Documents/secondstest/AI-Toolbox-master/src/Utils/Probability.cpp:1:
/home/goldencrow/Documents/secondstest/AI-Toolbox-master/include/AIToolbox/Utils/Core.hpp:6:10: fatal error: compare: No such file or directory
    6 | #include <compare>
      |          ^~~~~~~~~
compilation terminated.
make[2]: *** [src/CMakeFiles/AIToolboxMDP.dir/build.make:128: src/CMakeFiles/AIToolboxMDP.dir/Utils/Probability.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1140: src/CMakeFiles/AIToolboxMDP.dir/all] Error 2
make: *** [Makefile:95: all] Error 2
```

I'm not sure if I'm missing any dependency or something but I'm sure its a problem of my setup, I just can't get my finger on what could be missing.

EDIT: My gcc version is 9.3.0. GNU make is 4.2.1 and cmake 3.16.3
EDIT2: I've noticed that the missing library "<compare>" is from c++20 utility, could it be that I'm missing something on my system?

Thank you for your time,
Cassandro Martinho

**Comment by Svalorzen** [comment]
Yeah, I think that gcc 9 does not support c++20. gcc 10+ should work though. I assume on the system that works gcc is indeed version 10+.

**Comment by CassandroMartinho** [comment]
It seems that cmake is detecting the 9.3 version as you said. 
"-- The CXX compiler identification is GNU 9.3.0"

I've installed gcc 10+ with the following command
"sudo apt install gcc-10"

However it still seems like the cmake isn't detecting this. Any idea on what could be going wrong ? Do i need to manually install it or activate it somehow ?

**Comment by Svalorzen** [comment]
Can you try with

    CXX=g++-10 cmake ..

**Comment by CassandroMartinho** [comment]
Yes! That worked, thank you so much

**Comment by Svalorzen** [comment]
Perfect, no problem :)
