### ISSUE TITLE
Errors when compiling tutorials

### ISSUE THREAD

**Issue by stamourb** [Svalorzen/AI-Toolbox#55]
Whenever I try to compile any of the three tutorials (using the line `g++ -Iinclude -I/usr/local/include/eigen3 -std=c++20 examples/MDP/tiger_antelope.cpp` as an example, running from the AI-Toolbox-master directory, or running `g++ -I/home/ben/AI/AI-Toolbox-master/include -I/usr/local/include/eigen3 -std=c++20 tiger_antelope.cpp` from the directory containing the tutorial) I get a bunch of errors. I'm using C++ 20 and g++-10 and I have verified these using the --version options for each. I currently have installed Eigen using apt, but I originally tried downloading from the Eigen site and get the same errors either way. The first few errors I'm getting look like the following:

```
tiger_antelope.cpp:(.text+0x854): undefined reference to `AIToolbox::MDP::ValueIteration::ValueIteration(unsigned int, double, AIToolbox::MDP::ValueFunction)'
/usr/bin/ld: tiger_antelope.cpp:(.text+0x8d7): undefined reference to `AIToolbox::MDP::ValueIteration::getTolerance() const'
/usr/bin/ld: tiger_antelope.cpp:(.text+0x953): undefined reference to `AIToolbox::MDP::Policy::Policy(unsigned long, unsigned long, AIToolbox::MDP::ValueFunction const&)'
/usr/bin/ld: tiger_antelope.cpp:(.text+0x958): undefined reference to `AIToolbox::Impl::Seeder::getSeed()'
/usr/bin/ld: tiger_antelope.cpp:(.text+0x9ca): undefined reference to `AIToolbox::MDP::SparseModel::isTerminal(unsigned long) const'
```

And then after that, I get several errors that are similar to this:
```
/usr/bin/ld: /tmp/ccLrW1Ts.o: in function `Eigen::Matrix<double, -1, -1, 1, -1, -1> AIToolbox::MDP::computeQFunction<AIToolbox::MDP::SparseModel>(AIToolbox::MDP::SparseModel const&, Eigen::Matrix<double, -1, 1, 0, -1, 1> const&, Eigen::Matrix<double, -1, -1, 1, -1, -1>)':
tiger_antelope.cpp:(.text._ZN9AIToolbox3MDP16computeQFunctionINS0_11SparseModelEEEN5Eigen6MatrixIdLin1ELin1ELi1ELin1ELin1EEERKT_RKNS4_IdLin1ELi1ELi0ELin1ELi1EEES5_[_ZN9AIToolbox3MDP16computeQFunctionINS0_11SparseModelEEEN5Eigen6MatrixIdLin1ELin1ELi1ELin1ELin1EEERKT_RKNS4_IdLin1ELi1ELi0ELin1ELi1EEES5_]+0x3c): undefined reference to `AIToolbox::MDP::SparseModel::getA() const'
```

The final lines of errors are these:
```
/usr/bin/ld: /tmp/ccECV0k8.o:(.data.rel.ro._ZTIN9AIToolbox3MDP6PolicyE[_ZTIN9AIToolbox3MDP6PolicyE]+0x10): undefined reference to `typeinfo for AIToolbox::MDP::PolicyWrapper'
collect2: error: ld returned 1 exit status
```

I haven't been able to figure out how to fix any of this; most of it seems to be the tutorial programs being unable to access other files within other AI-Toolbox folders. I'd appreciate any help you could give on this!

**Comment by Svalorzen** [comment]
All examples should compile by default when running CMake and make. You should find the compiled executables inside the `examples` folder inside your build folder.

If you do want to compile them manually, what you are missing is that in your command you do not link the examples with the AI-Toolbox compiled libraries. This means that at linking time all its functions will not be found; that's the reason of the `undefined reference` errors.

**Comment by stamourb** [comment]
I know this is an old issue, but I just wanted to reopen this topic because I'd like to extend from my previous question a bit based on your answer:

If I wanted to compile the tutorials manually (or if I create a new program that uses some files from AI-Toolbox), you mentioned I'd have to link the programs with the AI-Toolbox compiled libraries. I have been using the following command to try to link a new program (called mdp2.cpp) with the AI-Toolbox libraries, but it does not work:

`g++ mdp2.cpp -L /home/ben/AI/AI-Toolbox-master/build -l AIToolboxMDP`

When I run that command, I get this error (which is the same error I get when I try to compile it without linking anything):

```
In file included from mdp2.cpp:9:
AI/AI-Toolbox-master/include/AIToolbox/MDP/Algorithms/ValueIteration.hpp:4:10: fatal error: AIToolbox/Impl/Logging.hpp: No such file or directory
    4 | #include <AIToolbox/Impl/Logging.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

I have also tried adding `-I /home/ben/AI/AI-Toolbox/master/include/AIToolbox/Impl` to my command, but it gives the same error. I assume I'm missing some steps or commands here, but I'm not sure what they are. I thought it might be because I'm not including a header file for the library in the program, but I couldn't find a header file for the library anywhere in the AI-Toolbox folders. I also looked in the AI-Toolbox README.md file but didn't see any instructions for how to link a program with the libraries. Any help you could give on this would be greatly appreciated!

**Comment by Svalorzen** [comment]
Have you tried `-I /home/ben/AI/AI-Toolbox/master/include/`?

In general I don't have any more instructions that I already have because these problems are mostly C++ specific rather than library specific; otherwise I might as well have a full C++ tutorial written in somewhere ;)

In any case, if you could get a bit familiar with CMake, it'd probably be less work to setup a C++ project that includes mine via CMake rather than keep working with compilation commands directly. I do have a project, [https://github.com/Svalorzen/AI-Toolbox-Experiments](https://github.com/Svalorzen/AI-Toolbox-Experiments), which I generally use as a base to run experiments for my research. It's not very documented because it's more for my personal use, but if you feel like looking at the CMakefiles a bit it might be easier to either use it or setup a CMake project yourself.

**Comment by stamourb** [comment]
Okay, thanks; I'll check them out. The libraries are still not linking properly, but I was able to get past the error I posted using `g++ mdp2.cpp -L /home/ben/AI/AI-Toolbox-master/build -l AIToolboxMDP -I /home/ben/AI/AI-Toolbox-master/include -I /usr/include/eigen3`.
