### ISSUE TITLE
Can't find Lpsolve when run cmake

### ISSUE THREAD

**Issue by Michaelxiaofeng** [Svalorzen/AI-Toolbox#56]
Hello, I created the folder "build" and have installed Lp-solve by "sudo apt install lp-solve", but when I tried to run cmake .., I was told "could not find LpSolve", would you please tell me how to fix this error? Thank you very much!
My system is Ubuntu 20.04.
By the way, boost and eigent3 can be found.

**Comment by saSerrano** [comment]
Hi @Michaelxiaofeng, with the following commands my CMakeLists.txt is able to find the LpSolve library (tested in Ubuntu 18.04):

wget http://bashdb.sf.net/lpsolve-5.5.0.10i.tar.bz2
tar -xpf lpsolve-5.5.0.10i.tar.bz2
cd ./lpsolve-5.5.0.10i
./configure --prefix=/usr && make && make check && sudo make install

Maybe what you need is to add the --prefix=/usr when you execute the configure file. Additionally, you may download a more recent version of LpSolve (I copy-pasted the one I am using).

I hope this helps :)

**Comment by Michaelxiaofeng** [comment]
> ./configure --prefix=/usr && make && make check && sudo make install

Thank you so much! I downloaded the newest version.
I tried , but got the error:./configure: permission denied
by the way , do we need to make ipsolve? I thought we just need to unzip the package and let cmake find the lib files.

**Comment by Svalorzen** [comment]
Hey, sorry for the late reply. Thankfully, this should be a pretty easy fix.

LpSolve comes with a program to solve linear programming problems. The `lpsolve` package you installed is that. However, it is not what this library used. Instead, you need to install the `liblpsolve55-dev` package. The `lib` and `dev` parts of the name are the hints that it is a development package, i.e. it contains the stuff required to use and link lpsolve features.

Do let us know if this fixes the problem.

**Comment by saSerrano** [comment]
As @Svalorzen so well explained it, yes you need to make lpsolve to use it in another project (e.g. AI-Toolbox).

Regarding the permission-denied error, try to execute the following command instead:
`sudo ./configure --prefix=/usr && make && make check && sudo make install`

I hope this fixes the problem.

**Comment by SinghGaganpreet** [comment]
I am also having the same problem. And the given command 
` sudo ./configure --prefix=/usr && make && make check && sudo make install`
is also giving permission error. 

I can see lp_solve "liblpsolve55.so" file in the /usr/lib/lp_solve" folder of my Ubuntu. But It's AI_Toolbox is not able to compile. 

Thanks for the help.

**Comment by SinghGaganpreet** [comment]
I tried installing thought "sudo apt install lp_solve", but I already had the newest lp_solve library. I checked and it was present in "/usr/lib/lp_solve"

But when I run the code, I get below mentioned error:

--```
 Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found suitable version "1.71.0", minimum required is "1.67")  
-- Found Eigen3: /usr/include/eigen3 (Required is at least version "3.2.92") 
CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find LpSolve (missing: LPSOLVE_LIBRARIES LPSOLVE_INCLUDE_PATH
  LPSOLVE_LINKS)
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  cmake/Modules/FindLpSolve.cmake:94 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:134 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/singh221/lib_required_for_vita/AI-Toolbox/build/CMakeFiles/CMakeOutput.log".

```

I even see set LPSOLVE_LIBRARIES=/usr/lib/  but no luck.

**Comment by Svalorzen** [comment]
You need to install `liblpsolve55-dev`. The `lp_solve` package is an executable, not for development.

**Comment by SinghGaganpreet** [comment]
Thanks, it is compiling but getting error while doing "make"

A new error thread was created for that (https://github.com/Svalorzen/AI-Toolbox/issues/59)
