### ISSUE TITLE
Not able to find "compare" file

### ISSUE THREAD

**Issue by SinghGaganpreet** [Svalorzen/AI-Toolbox#59]
`In file included from /home/singh221/lib_required_for_vita/AI-Toolbox/include/AIToolbox/Utils/Probability.hpp:8,
                 from /home/singh221/lib_required_for_vita/AI-Toolbox/src/Utils/Probability.cpp:1:

/home/singh221/lib_required_for_vita/AI-Toolbox/include/AIToolbox/Utils/Core.hpp:6:10: fatal error: compare: No such file or directory

    6 | #include <compare>
      |          ^~~~~~~~~
compilation terminated.

make[2]: *** [src/CMakeFiles/AIToolboxMDP.dir/build.make:128: src/CMakeFiles/AIToolboxMDP.dir/Utils/Probability.cpp.o] Error 1

make[1]: *** [CMakeFiles/Makefile2:1144: src/CMakeFiles/AIToolboxMDP.dir/all] Error 2
make: *** [Makefile:95: all] Error 2
`

**Comment by Svalorzen** [comment]
You need C++20 to compile the library. This means you need to have at least `g++-10` installed. What compiler are you using at the moment?

**Comment by SinghGaganpreet** [comment]
Upgraded and it is compiling perfectly. 
Thanks a lot!

**Comment by Svalorzen** [comment]
No problem, enjoy!
