### ISSUE TITLE
Better Project Setup Tutorial

### ISSUE THREAD

**Issue by Simonrazer** [Svalorzen/AI-Toolbox#63]
Hi! I am really struggling with the setup process. A short video of someone going through a "Hello World" type thing would do wonders, but a more detailed guide would be fine too.

**Comment by Svalorzen** [comment]
Hey, I think I could try to do something like that. What is your system? What exactly are you struggling with?

**Comment by Simonrazer** [comment]
I'm on Ubuntu 20.04, and I am stuck at the last section, Compiling a program. I don't know where to put my main.cpp (rn one of the examples), and I am not entirely sure about what libraries to link. When I try I most of the time get an error that either parts of AIToolbox or Eigen weren't found

**Comment by Svalorzen** [comment]
The repository is this one: https://github.com/Svalorzen/AI-Toolbox-Experiments

Please do let me know if you find the instructions understandable or if something is missing (you can open issues over there if you want).

If it works for you, then also let me know, and I will add a link to the repo in the main README here. Thanks!

**Comment by Simonrazer** [comment]
That really is quite an extensive stating point, but it works! Thank you!

**Comment by Svalorzen** [comment]
I'm happy it helps :) I've added the link to the README then. I'll close this, but feel free to open other issues (here or in the other repository) if you need more help.
