### ISSUE TITLE
C++: error: expected ‘)’ before ‘elementsN’

### ISSUE THREAD

**Issue by jmribeiro** [Svalorzen/AI-Toolbox#64]
[jacoposilvestrin@DLAI build]$ make
[  1%] Building CXX object src/CMakeFiles/AIToolboxMDP.dir/Seeder.cpp.o
[  2%] Building CXX object src/CMakeFiles/AIToolboxMDP.dir/Utils/Adam.cpp.o
[  3%] Building CXX object src/CMakeFiles/AIToolboxMDP.dir/Utils/Combinatorics.cpp.o
In file included from /home/jacoposilvestrin/Code/AI-Toolbox/src/Utils/Combinatorics.cpp:1:
/home/jacoposilvestrin/Code/AI-Toolbox/include/AIToolbox/Utils/Combinatorics.hpp:70:36: error: expected ‘)’ before ‘elementsN’
   70 |             SubsetEnumerator(size_t elementsN, Index lowerBound, Index upperBound) :
      |                             ~      ^~~~~~~~~~
      |                                    )
make[2]: *** [src/CMakeFiles/AIToolboxMDP.dir/build.make:104: src/CMakeFiles/AIToolboxMDP.dir/Utils/Combinatorics.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:102: src/CMakeFiles/AIToolboxMDP.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

**Comment by jmribeiro** [comment]
Additional info:

Cmake ran with:
cmake -DMAKE_POMDP=1 -DMAKE_PYTHON=1 -DAI_PYTHON_VERSION=3 ..

Boost: Boost-1.79.0

**Comment by Svalorzen** [comment]
Compiler version?

**Comment by jmribeiro** [comment]
> Compiler version?

12.1.0

**Comment by jmribeiro** [comment]
I've uninstalled Boost 1.79 and installed 1.75, compiled using g++-10, switched from Python 3.10 to 3.9, but am still getting the "use of deleted function boost::python..." errors. Do you know what might be the cause?

/home/jacoposilvestrin/Code/AI-Toolbox/src/Python/Types.cpp:28:82:   required from here
/usr/include/eigen3/Eigen/src/plugins/IndexedViewMethods.h:47:139: error: use of deleted function ‘boost::python::extract<int>::extract(const boost::python::extract<int>&)’
   47 | indices, internal::variable_if_dynamic<Index,ColsAtCompileTime>(derived().cols()),Specialized);

**Comment by Svalorzen** [comment]
I am on Boost 1.74 though, I hope the newer ones did not change too much; worst case you can let me know.

**Comment by Svalorzen** [comment]
Looked OK, I pushed to master; let me know if you still have issues.

**Comment by jmribeiro** [comment]
Will give it a go and get back to you!

**Comment by jmribeiro** [comment]
Perfect, it worked! Thank you so much.

Closing with this minor detail:
To use Boost 1.75 with Gcc 10, I used Python 3.9 instead of the latest (3.10).

I changed this in the CMakeLists.txt:

find_package(Python COMPONENTS Interpreter Development REQUIRED)
to 
find_package(Python 3.9 EXACT COMPONENTS Interpreter Development REQUIRED)

**Comment by Svalorzen** [comment]
I see.. I guess I could set it up so that if the AI_PYTHON_VERSION could also let you specify the subversion. But maybe it's not a huge deal. Happy it worked!
